repos:
  # Basic file checks - these only check, don't auto-fix
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-ast  # Verify Python syntax
      - id: check-case-conflict  # Check for files with names that would conflict on case-insensitive filesystems

  # Code formatting checks - CHECK ONLY, no auto-fixing
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3
        args: ['--check', '--diff']  # Only check, show diff of what would change

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--profile", "black", "--check-only", "--diff"]  # Only check, show diff

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        # Use the project's .flake8 config file for consistency
        # This ensures pre-commit uses the same rules as direct flake8 calls
        exclude: '^tests/'

  # Mypy is optional - uncomment if you want type checking
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.13.0
  #   hooks:
  #     - id: mypy
  #       additional_dependencies: []
  #       exclude: '^tests/'